### ISSUE TITLE
Add executeOnStart flag to WorkflowOptions

### ISSUE THREAD

**Issue by mfateev** [cadence-workflow/cadence#2103]
After the recent fix a cron workflow executes the first time after a delay. When used with schedule like "@every 6h" the first execution is 6h after start. There are use cases when customer wants immediate execution followed by the delay.

**Comment by vkuzmin-uber** [comment]
Instead of this flag I suggest to use pretty common patter with initial delay. Look at:
https://www.tutorialspoint.com/java/util/java_util_timer.htm

First:
The **scheduleAtFixedRate**(TimerTask task,**Date firstTime**,long period) method is used to schedule the specified task for repeated fixed-rate execution, beginning at the specified time.

and second:
The **scheduleAtFixedRate**(TimerTask task,**long delay**,long period) method is used to schedule the specified task for repeated fixed-rate execution, beginning after the specified delay.

**Comment by yux0** [comment]
StartWorkflowExecution will not do immediate execution. This is the fix YiChao has done. 
Currently, for users who want an immediate execution, one walkaround is to use SignalWithStartWorkflowExecution to run an immediate execution and then follow the cron schedule.

**Comment by simararneja** [comment]
@mfateev Any update on the timeline to get this done, would like to have this for a use case we are working on.

**Comment by simararneja** [comment]
@yux0 
> One walkaround is to use SignalWithStartWorkflowExecution to run an immediate execution and then follow the cron schedule.

This approach seems to support only typed workflow stubs. Any way same can be achieved with untyped ones ?

**Comment by demirkayaender** [comment]
This is done.
